version: '3.8'

services:
  app:
    build: .
    ports:
      - "7000:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./src/main/resources/application.properties:/app/src/main/resources/application.properties
    networks:
      - backend

networks:
  backend:
    driver: bridge

